title: OfferGo
description: OfferGo · 大厂算法面试备考
url: "https://mingsm17518.github.io"
markdown: kramdown
baseurl: "/OfferGo"

plugins:
  - jekyll-sitemap

include:
  - docs
  - _data

exclude:
  - README.md
  - requirements.txt
  - "*.py"
  - __pycache__
