title: EasyAlgo
description: 轻松学算法，从入门到实战
url: ""
markdown: kramdown
baseurl: ""

plugins:
  - jekyll-sitemap

include:
  - 00_python_basics
  - 01_data_structures
  - 02_algorithms
  - 03_leetcode_practice
  - 04_real_interviews
  - notes
  - docs
  - _data

exclude:
  - README.md
  - requirements.txt
  - "*.py"
  - __pycache__
